name: Daily Discord Notification

on:
  schedule:
    - cron: '50 22 * * *'  # 台灣時間 06:55 AM（UTC 22:55）
    - cron: '50 2 * * *'   # 台灣時間 10:55 AM（UTC 02:55）
    - cron: '50 6 * * *'   # 台灣時間 02:55 PM（UTC 06:55）
    - cron: '50 10 * * *'  # 台灣時間 06:55 PM（UTC 10:55）
    - cron: '50 14 * * *'  # 台灣時間 10:55 PM（UTC 14:55）
    - cron: '50 18 * * *'  # 台灣時間 02:55 AM（UTC 18:55）
  workflow_dispatch:  # 允許手動執行
jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "@everyone SvS about to begin！"}' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
