name: Daily Discord Notification

on:
  schedule:
    - cron: '0 10 * * *'  # 設定每天 UTC 10:00（台灣時間 18:00）執行

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "@everyone SvS about to begin！"}' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
